### ISSUE TITLE
swift3上面编译有些问题

### ISSUE THREAD

**Issue by yuanqingH** [Tangdixi/DCQRCode#2]
1、自定义运算符的写法在swift3上有了很大的改变
原： `infix operator >>> { associativity left }`
现：`infix operator >>> : ATPrecedence
precedencegroup ATPrecedence {
    associativity: left
    higherThan: AdditionPrecedence
    lowerThan: MultiplicationPrecedence
}`

2、func image() -> UIImage方法中image = UIGraphicsGetImageFromCurrentImageContext()这句会提示需要解包

**Comment by Tangdixi** [comment]
Fixed
